kind: PersistentVolume
apiVersion: v1
metadata:
  name: pv
  labels:
    type: local
spec:
  storageClassName: standard
  capacity:
    storage: 5Gi
  local:
    path: /data
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - mycluster-control-plane
  # nodeAffinity:
  #   required:
  #     nodeSelectorTerms:
  #       - matchExpressions:
  #         - key: app
  #           operator: In
  #           values:
  #             - globaleaks