apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-pvc
  labels:
    {{- include "globaleaks.labels" . | nindent 4 }}
spec:
  accessModes:
    - ReadWriteOnce #Many
  resources:
    requests:
      storage: {{ .Values.global.persistence.size }}
  storageClassName: {{ .Values.global.persistence.storageClass }}