apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-globaleaks
spec:
  selector:
    app: {{ .Release.Name }}-globaleaks
  ports:
  - name: http
    port: {{ .Values.service.port }}
    targetPort: 8080
  - name: https
    port: {{ .Values.service.httpsPort }}
    targetPort: 8443
  type: {{ .Values.service.type }}
